// libs/angular/features/git/src/lib/git-sync/git-sync.component.ts
import { Component, computed, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { GitStatusStore } from '@org/angular-data-access';
import { GitChangesStore } from '../git-changes.store';
import { GitCommitStore } from '../git-commit.store';

@Component({
  selector: 'ide-git-sync',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './git-sync.component.html',
  styleUrls: ['./git-sync.component.scss'],
})
export class GitSyncComponent {
  readonly gitStatusStore = inject(GitStatusStore);
  readonly changesStore = inject(GitChangesStore);
  readonly commitStore = inject(GitCommitStore);

  readonly hasStagedFiles = computed(() => {
    const tree = this.changesStore.changesTree();
    return tree?.directories.some((d) => d.path === '/staged') ?? false;
  });
  readonly isUntracked = computed(() => !this.gitStatusStore.tracking());
  readonly hasPendingSync = computed(
    () => (this.gitStatusStore.ahead() > 0 || this.isUntracked()) && !this.hasStagedFiles(),
  );
  readonly syncLabel = computed(() =>
    this.isUntracked() ? 'Publish Branch' : `Push (${this.gitStatusStore.ahead()})`,
  );

  onSync(): void {
    if (this.hasPendingSync()) {
      this.commitStore.sync();
    } else {
      this.onCommit();
    }
  }

  onCommit(): void {
    const trimmed = this.commitStore.commitMessage().trim();
    if (!trimmed) return;
    this.commitStore.commit(trimmed);
  }

  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) {
      this.onCommit();
    }
  }
}

// libs/react/features/git/src/lib/git-sync/git-sync.tsx
import { useGitCommitStore, useGitChangesStore } from '@org/react-data-access';
import { useGitStatusStore } from '@org/react-data-access';
import './git-sync.scss';

export function GitSync() {
  const commitMessage = useGitCommitStore((s) => s.commitMessage);
  const setCommitMessage = useGitCommitStore((s) => s.setCommitMessage);
  const commit = useGitCommitStore((s) => s.commit);
  const push = useGitCommitStore((s) => s.push);
  const isCommitting = useGitCommitStore((s) => s.isCommitting);
  const isPushing = useGitCommitStore((s) => s.isPushing);

  const ahead = useGitStatusStore((s) => s.ahead);
  const tracking = useGitStatusStore((s) => s.tracking);

  const changesTree = useGitChangesStore((s) => s.changesTree);
  const hasStagedFiles = changesTree?.directories.some((d) => d.path === '/staged') ?? false;

  const isUntracked = !tracking;
  const hasPendingSync = (ahead > 0 || isUntracked) && !hasStagedFiles;
  const syncLabel = isUntracked ? 'Publish Branch' : `Push (${ahead})`;

  function handleCommit() {
    const trimmed = commitMessage.trim();
    if (!trimmed || !hasStagedFiles) return;
    commit(trimmed);
  }

  function handleKeydown(event: React.KeyboardEvent) {
    if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) {
      handleCommit();
    }
  }

  return (
    <div className="commit-input">
      <textarea
        className="message-input"
        placeholder="Message (Ctrl+Enter to commit)"
        value={commitMessage}
        onChange={(e) => setCommitMessage(e.target.value)}
        onKeyDown={handleKeydown}
        rows={1}
      />
      {hasPendingSync ? (
        <button className="commit-button sync" onClick={push} disabled={isPushing}>
          {syncLabel}
        </button>
      ) : (
        <button
          className="commit-button"
          disabled={!commitMessage.trim() || !hasStagedFiles || isCommitting}
          onClick={handleCommit}
        >
          Commit
        </button>
      )}
    </div>
  );
}
