// libs/react/features/code-editor/src/lib/monaco-editor/monaco-editor.tsx
import { useEffect, useRef } from 'react';
import { MonacoUtils } from '@org/shared/utils';
import { useCodeEditorStore } from '@org/react-data-access';
import './monaco-editor.scss';

export function MonacoEditor() {
  const containerRef = useRef<HTMLDivElement>(null);

  const activeFile = useCodeEditorStore((s) => {
    const path = s.activeFilePath;
    return s.openFiles.find((f) => f.path === path) ?? null;
  });

  useEffect(() => {
    MonacoUtils.editorUtils.loadMonaco().then(() => {
      if (containerRef.current && !MonacoUtils.editorUtils.isReady) {
        MonacoUtils.editorUtils.create(containerRef.current, handleSave);
      }
    });
  }, []);

  useEffect(() => {
    MonacoUtils.editorUtils.switchToFile(activeFile, handleContentChange);
  }, [activeFile?.path]);

  return <div ref={containerRef} className="editor-container" />;
}

function handleSave(): void {
  const { activeFilePath, saveFile } = useCodeEditorStore.getState();
  if (activeFilePath) saveFile(activeFilePath);
}

function handleContentChange(path: string, value: string): void {
  useCodeEditorStore.getState().updateContent(path, value);
}

// libs/angular/features/code-editor/src/lib/monaco-editor/monaco-editor.component.ts
import { Component } from '@angular/core';
import { MonacoUtils } from '@org/shared/utils';
import { editor } from '@org/angular-data-access';
import { MonacoBaseComponent } from '../monaco-base/monaco-base.component';

@Component({
  selector: 'ide-monaco-editor',
  standalone: true,
  templateUrl: './monaco-editor.component.html',
  styleUrls: ['./monaco-editor.component.scss'],
})
export class MonacoEditorComponent extends MonacoBaseComponent {
  private monacoEditor = new MonacoUtils.MonacoEditorUtils(this.loader);

  protected isReady(): boolean {
    return this.monacoEditor.isReady;
  }

  protected createEditor(container: HTMLElement): void {
    this.monacoEditor.create(container, this.save);
  }

  protected switchToFile(file: editor.OpenFile | null): void {
    this.monacoEditor.switchToFile(file, this.onContentChange);
  }

  ngOnDestroy(): void {
    this.monacoEditor.dispose();
  }

  private save = (): void => {
    const path = this.store.activeFilePath();
    if (path) this.store.saveFile(path);
  };

  private onContentChange = (path: string, value: string): void => {
    this.store.updateContent(path, value);
  };
}
