// libs/react/features/ide/src/lib/file-search/file-search.tsx
import { useCallback, useState } from 'react';
import { CommandPalette, CommandPaletteItem } from '@org/react-ui';
import { fileExplorerService, useAuthStore, useCodeEditorStore } from '@org/react-data-access';

interface FileSearchProps {
  onClose: () => void;
}

export function FileSearch({ onClose }: FileSearchProps) {
  const [items, setItems] = useState<CommandPaletteItem[]>([]);
  const [loading, setLoading] = useState(false);

  const onSearchChanged = useCallback(async (query: string) => {
    if (!query.trim()) {
      setItems([]);
      return;
    }

    const rootPath = useAuthStore.getState().workspace?.rootPath;
    if (!rootPath) return;

    setLoading(true);
    const { success, data } = await fileExplorerService.searchFiles(query, rootPath);
    setLoading(false);

    if (success) {
      setItems(data.map((file) => ({ id: file.path, label: file.name, description: file.path })));
    }
  }, []);

  const onItemSelected = useCallback(
    (item: CommandPaletteItem) => {
      onClose();
      useCodeEditorStore.getState().fetchAndOpenFile(item.id);
    },
    [onClose],
  );

  return (
    <CommandPalette
      items={items}
      placeholder="Search files by name..."
      loading={loading}
      onItemSelected={onItemSelected}
      onSearchChanged={onSearchChanged}
      onClose={onClose}
    />
  );
}

// libs/angular/features/ide/src/lib/file-search/file-search.component.ts
import { Component, computed, inject, OnDestroy, output } from '@angular/core';
import { FileResponseDto } from '@org/shared/contracts';
import { CommandPaletteComponent, CommandPaletteItem } from '@org/angular/ui';
import { FileSearchStore } from './file-search.store';

@Component({
  selector: 'ide-file-search',
  standalone: true,
  imports: [CommandPaletteComponent],
  providers: [FileSearchStore],
  templateUrl: './file-search.component.html',
})
export class FileSearchComponent implements OnDestroy {
  readonly fileSelected = output<FileResponseDto>();
  readonly closed = output<void>();

  private readonly store = inject(FileSearchStore);

  readonly loading = this.store.searchLoading;
  readonly items = computed<CommandPaletteItem[]>(() =>
    this.store.searchResults().map((file) => ({
      id: file.path,
      label: file.name,
      description: file.path,
    })),
  );

  onSearchChanged(query: string): void {
    if (!query.trim()) {
      this.store.clearSearchResults();
      return;
    }
    this.store.searchFiles(query);
  }

  onItemSelected(item: CommandPaletteItem): void {
    const file = this.store.searchResults().find((f) => f.path === item.id);
    if (file) {
      this.fileSelected.emit(file);
    }
  }

  ngOnDestroy(): void {
    this.store.clearSearchResults();
  }
}
