// libs/angular/shared/ui/src/lib/confirmation-dialog/confirmation-dialog.component.ts
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'ui-confirmation-dialog',
  standalone: true,
  template: `
    @if (isOpen()) {
      <div class="backdrop" (click)="cancelled.emit()">
        <div class="dialog" (click)="$event.stopPropagation()">
          <div class="dialog-title">{{ title() }}</div>
          <div class="dialog-message">{{ message() }}</div>
          <div class="dialog-actions">
            <button class="btn btn-cancel" (click)="cancelled.emit()">Cancel</button>
            <button class="btn btn-confirm" (click)="confirmed.emit()">Confirm</button>
          </div>
        </div>
      </div>
    }
  `,
  styleUrls: ['./confirmation-dialog.component.scss'],
})
export class ConfirmationDialogComponent {
  isOpen = input.required<boolean>();
  title = input<string>('');
  message = input<string>('');
  confirmed = output();
  cancelled = output();
}

// libs/react/shared/ui/src/lib/confirmation-dialog/confirmation-dialog.tsx
import './confirmation-dialog.scss';

interface ConfirmationDialogProps {
  isOpen: boolean;
  title: string;
  message: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmationDialog({ isOpen, title, message, onConfirm, onCancel }: ConfirmationDialogProps) {
  if (!isOpen) return null;

  return (
    <div className="backdrop" onClick={onCancel}>
      <div className="dialog" onClick={(e) => e.stopPropagation()}>
        <div className="dialog-title">{title}</div>
        <div className="dialog-message">{message}</div>
        <div className="dialog-actions">
          <button className="btn btn-cancel" onClick={onCancel}>Cancel</button>
          <button className="btn btn-confirm" onClick={onConfirm}>Confirm</button>
        </div>
      </div>
    </div>
  );
}
